import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = cookies().get('user_session')?.value || null;
  return (
    <html data-theme="light" lang="en">
      <body className={inter.className}>
        <Navbar session={session}/>
        <main className="flex min-h-screen flex-col items-center justify-between px-24">
          {children}
          </main>
      </body>
    </html>
  );
}
